### ISSUE TITLE
Pre-commit dependency `flake8`

### ISSUE THREAD

**Issue by Anselmoo** [mwouts/itables#124]
The `gitlab` dependency requires for `flake8` requires an account.

https://github.com/mwouts/itables/blob/d12e364690afb788947890080fa380af92eb3c4d/.pre-commit-config.yaml#L14-L17

More convenient would be:

```yaml
- repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
 ```
