### ISSUE TITLE
Deploy a sample Shiny app that uses ITables

### ISSUE THREAD

**Issue by mwouts** [mwouts/itables#276]
This can be done using https://shiny.posit.co/py/docs/shinylive.html.

See also https://www.appsilon.com/post/shiny-for-python-deploy-github-pages

**Comment by fredguth** [comment]
I have a working example here: https://github.com/fredguth/shinyduck/blob/main/express-itables-mwe.py

**Comment by micboat** [comment]
> @fredguth thanks for sharing. If I have a custom css. how do I apply it to the itable  output within my shiny express app.  

```css = """
.dt-container {
  font-size: small;
}

.dataTable th {
  font-weight: bolder;
  background-color: #e1e6ec;
  color: #120051;
  text-align: center !important;
}

.dataTable tbody {
  background-color: white;
  color: #120051;
}

/* Left-align the first visible column (index) */
.dataTable td:first-child,
.dataTable th:first-child {
  text-align: left !important;
}

/* Center-align all other columns */
.dataTable td:not(:first-child),
.dataTable th:not(:first-child) {
  text-align: center !important;
}
"""
``` 

often within ipython  notebooks I can do  this to apply to all tables

```
display(HTML(f"<style>{css}</style>" ""))
```
